# File: .azure-ci/jobs/bottles-build.yml

parameters:
  name: ''
  displayName: ''
  vmImage: ''

jobs:

- job: ${{ parameters.name }}
  displayName: "${{ parameters.displayName }}"

  pool:
    vmImage: ${{ parameters.vmImage }}

  dependsOn: []

  variables:
    os_version: ${{ parameters.vmImage }}

  steps:

    # Setup CI environment
    - template: /.azure-ci/steps/setup-ci-env.yml

    # Checkout PR branch
    - template: /.azure-ci/steps/checkout-pr.yml

    # Install your tap
    - template: /.azure-ci/steps/install-tap.yml

    # When working on a fork of homebrew/test-bot, run this step to tap your
    # repository and checkout the correct feature branch
    - template: /.azure-ci/steps/tap-dev-test-bot.yml

    - bash: |
        brew test-bot --root-url=$(bintray_root_url)
      displayName: Run brew test-bot
      env:
        UPSTREAM_GIT_URL: $(UPSTREAM_GIT_URL)
        UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)

    - script: |
        RANDOM_ARTIFACT_ID="$(uuidgen)"
        echo "Random Formula ID is: $RANDOM_ARTIFACT_ID"
        echo "##vso[task.setvariable variable=artifact_id;isOutput=true]$RANDOM_ARTIFACT_ID"
      displayName: Set formula variable
      name: set_artifact_id

    - bash: |
        cp *.bottle.* $(Build.ArtifactStagingDirectory)
      displayName: Copy json & bottle files

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: $(set_artifact_id.artifact_id)-bottle-$(os_version)
        targetPath: $(Build.ArtifactStagingDirectory)
      displayName: Publish formula-bottle-$(os_version)
