# File: .azure-ci/jobs/test-template.yml

parameters:
  name: ''
  message: ''

jobs:
  - job: ${{ parameters.name }}
    displayName: Job - ${{ parameters.message }}

    timeoutInMinutes: 0

    pool:
      vmImage: macOS-10.14
    steps:
      - bash: |
          echo ${{ parameters.message }}
          git log
          git show
          echo $RANDOM
        displayName: Step - ${{ parameters.message }}
