# File: .azure-ci/stages/stage-upload-bottles.yml

# Stage 4 - Uploading bottles to Bintray

stages:

  - stage: stage_upload_bottles
    displayName: Stage - Upload bottles

    dependsOn:
      - stage_build_bottles

    condition: |
      and(
        succeeded('stage_build_bottles'),
        eq(variables['System.PullRequest.IsFork'], False),
        not(contains(variables['Build.SourceVersionMessage'], 'skip-upload')),
        eq(variables['Build.Reason'], 'PullRequest')
      )

    jobs:

      - job: brew_test_bot_ci_upload
        displayName: Job - Upload bottles

        pool:
          vmImage: macOS-latest

        steps:

          - task: InstallSSHKey@0
            inputs:
              hostName: $(ssh_hostname)
              sshPublicKey: $(ssh_public_key)
              sshPassphrase: $(ssh_passphrase) # Optional
              sshKeySecureFile: $(ssh_secure_file)

          - template: /.azure-ci/steps/setup-ci-env.yml

          # When working on a fork of homebrew/test-bot, run this step to tap your
          # repository and checkout the correct feature branch
          - template: /.azure-ci/steps/tap-dev-test-bot.yml

          - task: DownloadPipelineArtifact@1
            inputs:
              itemPattern: '**'
              downloadPath: $(System.DefaultWorkingDirectory)
            displayName: Download artifacts

          - bash: |
              mv *-bottle-*/* ./
              rm -rf *-bottle-*
            displayName: Move bottle files to cwd

          - bash: |
              brew test-bot --verbose --ci-upload --bintray-org=$(bintray_org) --git-name=$(github_user) --git-email=$(github_email)
            displayName: Run brew test-bot --ci-upload
            env:
              HOMEBREW_BINTRAY_USER: $(HOMEBREW_BINTRAY_USER)
              HOMEBREW_BINTRAY_KEY: $(HOMEBREW_BINTRAY_KEY)
              UPSTREAM_GIT_URL: $(UPSTREAM_GIT_URL)
              UPSTREAM_PULL_REQUEST: $(UPSTREAM_PULL_REQUEST)
