# File: .azure-ci/stages/stage-test-formulae.yml

# Stage 1 - Testing formulae on master

stages:

  - stage: stage_test_formulae_on_master
    displayName: Stage - Test Formulae on master

    condition: |
      or(
        eq(variables['Build.Reason'], 'IndividualCI')
        ,and(
          eq(variables['Build.Reason'], 'PullRequest')
          ,contains(variables['System.PullRequest.SourceBranch'], 'dev_test_formulae')
        )
      )

    jobs:

      - job: job_test_formulae
        displayName: Job - Test formulae on master

        pool:
          vmImage: macOS-10.14

        steps:

          # Setup CI environment
          - template: /.azure-ci/steps/setup-ci-env.yml

          # Install tap
          - template: /.azure-ci/steps/install-tap.yml

          # When working on a fork of homebrew/test-bot, run this step to tap your
          # repository and checkout the correct feature branch
          # - template: /.azure-ci/steps/tap-dev-test-bot.yml

          # Test formulae
          - template: /.azure-ci/steps/test-formulae.yml

      - job: job_create_revision_bump_pr
        displayName: Job - Create revision bump PR

        pool:
          vmImage: macOS-10.14

        dependsOn: job_test_formulae

        condition: |
          and(
            succeeded('job_test_formulae'),
            ne(dependencies.job_test_formulae.outputs['test_formulae.failing_formulae'], '')
          )

        variables:
          failing_formulae: $[ dependencies.job_test_formulae.outputs['test_formulae.failing_formulae'] ]

        steps:

          # Setup CI environment
          - template: /.azure-ci/steps/setup-ci-env.yml

          # Install tap
          - template: /.azure-ci/steps/install-tap.yml

          # Test formulae
          - template: /.azure-ci/steps/create-bump-revision-pr.yml
            parameters:
              stage_name: "master commit CI"
