# File: .azure-ci/stages/stage-scheduled-test-from-bottles.yml

# Stage 2 - Cron job to test formulae

stages:

  - stage: stage_scheduled_test
    displayName: Stage - Scheduled Test on master

    dependsOn: []

    condition: |
      or(
        eq(variables['Build.Reason'], 'Schedule')
        ,and(
          eq(variables['Build.Reason'], 'PullRequest')
          ,contains(variables['System.PullRequest.SourceBranch'], 'dev_scheduled_test')
        )
      )

    jobs:

      - job: job_scheduled_test
        displayName: Job - Scheduled Test on master

        pool:
          vmImage: macOS-latest

        steps:

          # Setup CI environment
          - template: /.azure-ci/steps/setup-ci-env.yml

          # Install tap
          - template: /.azure-ci/steps/install-tap.yml

          # Test formulae
          - template: /.azure-ci/steps/test-formulae-from-bottles.yml

      - job: job_create_revision_bump_pr
        displayName: Job - Create revision bump PR

        pool:
          vmImage: macOS-latest

        dependsOn: job_scheduled_test

        condition: |
          and(
            failed('job_scheduled_test'),
            ne(dependencies.job_scheduled_test.outputs['test_formulae.failing_formulae'], '')
          )

        variables:
          failing_formulae: $[ dependencies.job_scheduled_test.outputs['test_formulae.failing_formulae'] ]

        steps:

          # Setup CI environment
          - template: /.azure-ci/steps/setup-ci-env.yml

          # Install tap
          - template: /.azure-ci/steps/install-tap.yml

          # Test formulae
          - template: /.azure-ci/steps/create-bump-revision-pr.yml
            parameters:
              stage_name: "scheduled CI"
