# File: .azure-ci/stages/stage-scheduled-test-from-source.yml

# Stage 2 - Cron job to test formulae

stages:

  - stage: stage_scheduled_test_from_source
    displayName: Stage - Scheduled Test on master (build from source)

    dependsOn: []

    condition: |
      or(
        eq(variables['Build.Reason'], 'Schedule')
        ,and(
          eq(variables['Build.Reason'], 'PullRequest')
          ,contains(variables['System.PullRequest.SourceBranch'], 'dev_scheduled_test_from_source')
        )
      )

    jobs:

      - job: job_scheduled_test
        displayName: Job - Scheduled Test on master

        pool:
          vmImage: macOS-latest

        steps:

          # Setup CI environment
          - template: /.azure-ci/steps/setup-ci-env.yml

          # Install tap
          - template: /.azure-ci/steps/install-tap.yml

          # When working on a fork of homebrew/test-bot, run this step to tap your
          # repository and checkout the correct feature branch
          - template: /.azure-ci/steps/tap-dev-test-bot.yml

          # Test formulae
          - template: /.azure-ci/steps/test-formulae-from-source.yml
