# File: .azure-ci/stages/stage-build-bottles.yml

# Stage 3 - Building bottles on PR

stages:

  - stage: stage_build_bottles
    displayName: Stage - Build bottles

    dependsOn: []

    condition: |
      and(
        eq(variables['Build.Reason'], 'PullRequest')
        ,not(contains(variables['Build.SourceVersionMessage'], 'skip-bottles'))
      )

    jobs:

      - template: /.azure-ci/jobs/bottles-build.yml
        parameters:
          name: brew_test_bot_macOS_10_15
          displayName: Job - For macOS Catalina (10.15)
          vmImage: macOS-latest

      - template: /.azure-ci/jobs/bottles-build.yml
        parameters:
          name: brew_test_bot_macOS_10_14
          displayName: Job - For macOS Mojave (10.14)
          vmImage: macOS-10.14

      - template: /.azure-ci/jobs/bottles-build.yml
        parameters:
          name: brew_test_bot_macOS_10_13
          displayName: Job - For macOS High Sierra (10.13)
          vmImage: macOS-10.13
